### ISSUE TITLE
SVG 注意事項

### ISSUE THREAD

**Issue by osk2** [ProjectWmega/web#3]
## 繪圖

- 地圖同一圖層
- 簡化地圖形狀
- 圖層名稱或id不可重複
- 不設定字型（使用預設）<sup>1</sup>
- 統一字體大小 <sup>2</sup>
- 盡量不插入文字 <sup>3</sup>

## 匯出

- 小數點一位 <sup>4</sup>
- 字體問題 <sup>3</sup>

## 後製程序

- 將颱風眼轉為`circle`
- 將路徑轉為`polyline`

### 註
<sup>1</sup>
設定的字型在其他系統上沒有安裝，如圖，Windows上沒有蘋果儷黑，就會用新細明體替代（或預設字體）
![font-family](https://cloud.githubusercontent.com/assets/705280/24070891/b367474e-0c00-11e7-83e0-4dc1e2fd0616.png)

<sup>2</sup>
不確定illustrator如何指定字體大小，svg中看起來數值精細到小數點第三位（在網頁中通常不使用小數點）
![font-size](https://cloud.githubusercontent.com/assets/705280/24070894/c75867d8-0c00-11e7-955d-bdf670bf4df9.png)

指定字體大小後，同樣的大小可以共享一樣的class，可以減少資料量

<sup>3</sup>
非必要避免在svg中插入文字，因為插入的文字也會被轉換成用svg表示，導致svg的資料量大增

如下圖，紅框中分別為「大」和「心」，文字若用網頁追加上去可以大幅減少資料量
![screen shot 2017-03-17 at 11 39 36 am](https://cloud.githubusercontent.com/assets/705280/24070898/f56cd0fa-0c00-11e7-896f-96c3dec31b79.png)

<sup>4</sup>
小數精度到一位也不會產生太大偏差，也可以讓svg更簡潔

**Comment by mapleegg** [comment]
已製作完成！
