### ISSUE TITLE
颱風路徑選擇性顯示

### ISSUE THREAD

**Issue by osk2** [ProjectWmega/web#5]
![screen shot 2017-03-19 at 9 45 43 pm](https://cloud.githubusercontent.com/assets/705280/24081385/7001aca4-0ced-11e7-89bb-5a18fb6b219b.png)

**Comment by mapleegg** [comment]
颱風頁面呈現動畫順序步驟
@osk2 

 1. 地圖一開始就有
 2. 城市名稱淡出
 3. 暴風圈由圓心擴散出來，並跳出現在位置與時間資訊看板
 4. 路徑跑出
 5. 資訊看板跳出

**Comment by osk2** [comment]
@mapleegg 我把它獨立到 #8

**Comment by osk2** [comment]
Resolved in 13cc3f69f9f4775b334d43d35c9cb7dc2e9df3ed
